"""
sft_train.py

SFT warm-start: fine-tune Qwen2-VL-2B-Instruct on oracle-generated examples
before GRPO so the model learns to read state numbers and produce valid actions.

Reads : /model-cache/sft_data.jsonl   (generated by generate_sft_data.py)
Saves : /model-cache/checkpoints/sft_warmstart/

Run with:
    modal run sft_train.py
    modal run sft_train.py --n-epochs 3 --lr 2e-5

Then pass the checkpoint into GRPO:
    modal run run_train_m6.py  (edit GRPOTrainer to load sft_warmstart first)
"""

import modal
from modal_config import app, rl_image, model_volume, MODEL_CACHE_DIR


@app.function(
    image=rl_image,
    gpu="A10G",
    volumes={MODEL_CACHE_DIR: model_volume},
    timeout=3600 * 4,
)
def run_sft_training(
    n_epochs         : int   = 2,
    lr               : float = 2e-5,
    grad_accum_steps : int   = 8,
    lora_rank        : int   = 8,
    max_examples     : int   = 0,   # 0 = use all
    eval_every       : int   = 100, # print generated think text every N steps (0 = off)
) -> dict:
    import os, json, random, base64, io
    import numpy as np

    os.environ["HF_HOME"]            = MODEL_CACHE_DIR
    os.environ["TRANSFORMERS_CACHE"] = MODEL_CACHE_DIR

    import torch
    import torch.nn.functional as F
    from transformers import Qwen2VLForConditionalGeneration, AutoProcessor
    from peft import get_peft_model, LoraConfig
    from PIL import Image
    from qwen_vl_utils import process_vision_info
    from policy import SYSTEM_PROMPT, USER_PROMPT_TEMPLATE

    print("\n" + "=" * 60)
    print("  SFT WARM-START TRAINING")
    print("=" * 60)

    # ------------------------------------------------------------------
    # 1. Load data
    # ------------------------------------------------------------------
    data_path = os.path.join(MODEL_CACHE_DIR, "sft_data.jsonl")
    print(f"\n[1/4] Loading SFT data from {data_path}...")

    examples = []
    with open(data_path) as f:
        for line in f:
            examples.append(json.loads(line))

    if max_examples > 0:
        examples = examples[:max_examples]

    random.shuffle(examples)

    phase_counts: dict = {}
    for ex in examples:
        phase_counts[ex["phase"]] = phase_counts.get(ex["phase"], 0) + 1
    print(f"  {len(examples)} examples  phases: {phase_counts}")

    # ------------------------------------------------------------------
    # 2. Load model + LoRA
    # ------------------------------------------------------------------
    print(f"\n[2/4] Loading model + LoRA (rank={lora_rank})...")

    base_model = Qwen2VLForConditionalGeneration.from_pretrained(
        "Qwen/Qwen2-VL-2B-Instruct",
        torch_dtype=torch.float16,
        device_map="auto",
        cache_dir=MODEL_CACHE_DIR,
    )
    processor = AutoProcessor.from_pretrained(
        "Qwen/Qwen2-VL-2B-Instruct",
        cache_dir=MODEL_CACHE_DIR,
    )

    lora_cfg = LoraConfig(
        r              = lora_rank,
        lora_alpha     = lora_rank * 2,
        target_modules = ["q_proj", "v_proj"],
        lora_dropout   = 0.05,
        bias           = "none",
        task_type      = "CAUSAL_LM",
    )
    model = get_peft_model(base_model, lora_cfg)
    model.enable_input_require_grads()
    model.gradient_checkpointing_enable()
    model.print_trainable_parameters()
    model.train()

    optimizer = torch.optim.Adam(
        [p for p in model.parameters() if p.requires_grad], lr=lr
    )

    # ------------------------------------------------------------------
    # 3. Loss function for one example
    # ------------------------------------------------------------------
    def compute_loss(ex: dict) -> torch.Tensor:
        # Decode stored frame
        pil_image = Image.open(
            io.BytesIO(base64.b64decode(ex["frame_b64"]))
        ).resize((224, 224), Image.LANCZOS)

        # Rebuild user prompt — must match inference-time format exactly
        achieved  = [round(v, 4) for v in ex["achieved_goal"]]
        desired   = [round(v, 4) for v in ex["desired_goal"]]
        distance  = float(np.linalg.norm(
            np.array(ex["desired_goal"]) - np.array(ex["achieved_goal"])
        ))
        user_text = USER_PROMPT_TEMPLATE.format(
            achieved_goal=achieved, desired_goal=desired, distance=distance
        )

        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": [
                {"type": "image", "image": pil_image},
                {"type": "text",  "text": user_text},
            ]},
        ]

        # Prompt-only pass — find where response tokens start.
        # apply_chat_template with add_generation_prompt=True appends <think>
        # so the response is everything after that opening tag.
        text_input     = processor.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        img_inputs, vid_inputs = process_vision_info(messages)

        prompt_enc = processor(
            text=[text_input], images=img_inputs, videos=vid_inputs,
            return_tensors="pt", padding=True,
        )
        prompt_len = prompt_enc["input_ids"].shape[1]
        del prompt_enc

        # Target response: think content + </think> + action tag.
        # <think> is already in the prompt (from add_generation_prompt),
        # so we only provide what comes after it.
        action_str = str(ex["action"])   # e.g. "[0.5, -0.3, 0.8, 1.0]"
        response   = f"{ex['think']}\n</think>\n<action>{action_str}</action>"
        full_text  = text_input + response

        full_enc = processor(
            text=[full_text], images=img_inputs, videos=vid_inputs,
            return_tensors="pt", padding=True,
        ).to("cuda")

        outputs = model(**full_enc, use_cache=False)
        logits  = outputs.logits   # (1, seq_len, vocab_size)

        # Slice to response tokens only (same shift as _step_log_prob in trainer.py)
        resp_logits    = logits[:, prompt_len - 1 : -1, :]
        resp_token_ids = full_enc["input_ids"][:, prompt_len:]

        return F.cross_entropy(
            resp_logits.squeeze(0),
            resp_token_ids.squeeze(0),
        )

    # ------------------------------------------------------------------
    # 3b. Quick eval helper — generates think text for one fixed example
    # ------------------------------------------------------------------
    eval_ex = examples[0]   # fixed reference example (shuffled, so just first)

    def quick_eval(label: str) -> None:
        """Generate think text for the fixed eval example and print it."""
        import base64, io
        model.eval()
        with torch.no_grad():
            pil_image = Image.open(
                io.BytesIO(base64.b64decode(eval_ex["frame_b64"]))
            ).resize((224, 224), Image.LANCZOS)

            achieved = [round(v, 4) for v in eval_ex["achieved_goal"]]
            desired  = [round(v, 4) for v in eval_ex["desired_goal"]]
            dist     = float(np.linalg.norm(
                np.array(eval_ex["desired_goal"]) - np.array(eval_ex["achieved_goal"])
            ))
            user_text = USER_PROMPT_TEMPLATE.format(
                achieved_goal=achieved, desired_goal=desired, distance=dist
            )
            messages = [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": [
                    {"type": "image", "image": pil_image},
                    {"type": "text",  "text": user_text},
                ]},
            ]
            text_input = processor.apply_chat_template(
                messages, tokenize=False, add_generation_prompt=True
            )
            img_inputs, vid_inputs = process_vision_info(messages)
            enc = processor(
                text=[text_input], images=img_inputs, videos=vid_inputs,
                return_tensors="pt", padding=True,
            ).to("cuda")

            out        = model.generate(**enc, max_new_tokens=100, do_sample=False)
            new_tokens = out[0][enc["input_ids"].shape[1]:]
            text       = processor.tokenizer.decode(new_tokens, skip_special_tokens=True)

        model.train()
        print(f"\n  [EVAL {label}]")
        print(f"  state: achieved={achieved}  desired={desired}  phase={eval_ex['phase']}")
        print(f"  generated: {text[:400]}")
        print()

    # ------------------------------------------------------------------
    # 4. Training loop
    # ------------------------------------------------------------------
    steps_per_epoch = len(examples)
    total_steps     = n_epochs * steps_per_epoch
    est_min         = total_steps * 0.5 / 60   # ~0.5 s/step on A10G
    print(f"\n[3/4] Training: {n_epochs} epochs  lr={lr}  grad_accum={grad_accum_steps}...")
    print(f"  {total_steps} total steps  estimated {est_min:.0f}–{est_min*2:.0f} min on A10G")

    loss_history = []
    global_step  = 0

    if eval_every > 0:
        quick_eval("before training")

    for epoch in range(n_epochs):
        random.shuffle(examples)
        epoch_loss  = 0.0
        optimizer.zero_grad()

        for i, ex in enumerate(examples):
            torch.cuda.empty_cache()

            loss = compute_loss(ex) / grad_accum_steps
            loss.backward()
            epoch_loss += loss.item() * grad_accum_steps

            # Step whenever accumulation window fills or we hit the last example
            if (i + 1) % grad_accum_steps == 0 or (i + 1) == len(examples):
                torch.nn.utils.clip_grad_norm_(
                    [p for p in model.parameters() if p.requires_grad], 1.0
                )
                optimizer.step()
                optimizer.zero_grad()

            global_step += 1

            if (i + 1) % 50 == 0:
                avg = epoch_loss / (i + 1)
                print(f"  epoch {epoch+1}  step {i+1}/{len(examples)}  loss={avg:.4f}")

            if eval_every > 0 and global_step % eval_every == 0:
                quick_eval(f"epoch {epoch+1} step {i+1}")

            if global_step % 500 == 0:
                ckpt_path = os.path.join(MODEL_CACHE_DIR, "checkpoints", "sft_warmstart")
                os.makedirs(ckpt_path, exist_ok=True)
                model.save_pretrained(ckpt_path)
                model_volume.commit()
                print(f"  [checkpoint] step {global_step} → {ckpt_path}")

        avg_epoch_loss = epoch_loss / len(examples)
        loss_history.append(round(avg_epoch_loss, 4))
        print(f"  === Epoch {epoch+1} complete  avg_loss={avg_epoch_loss:.4f} ===\n")
        if eval_every > 0:
            quick_eval(f"end of epoch {epoch+1}")

        # Save after every epoch so a mid-training cancellation doesn't lose work
        ckpt_path = os.path.join(MODEL_CACHE_DIR, "checkpoints", "sft_warmstart")
        os.makedirs(ckpt_path, exist_ok=True)
        model.save_pretrained(ckpt_path)
        model_volume.commit()
        print(f"  Checkpoint saved → {ckpt_path}")

    # ------------------------------------------------------------------
    # 5. Final summary
    # ------------------------------------------------------------------
    print(f"  Loss trend: {loss_history}")
    print("=" * 60)

    return {
        "status"     : "PASS",
        "n_examples" : len(examples),
        "n_epochs"   : n_epochs,
        "loss_trend" : loss_history,
        "ckpt_path"  : ckpt_path,
    }


# ---------------------------------------------------------------------------
# Local entrypoint
# ---------------------------------------------------------------------------

@app.local_entrypoint()
def main(
    n_epochs         : int   = 2,
    lr               : float = 2e-5,
    grad_accum_steps : int   = 8,
    eval_every       : int   = 100,
):
    print(f"\nDispatching SFT training to Modal (A10G)...")
    print(f"  epochs={n_epochs}  lr={lr}  grad_accum={grad_accum_steps}  eval_every={eval_every}\n")

    result = run_sft_training.remote(
        n_epochs=n_epochs, lr=lr, grad_accum_steps=grad_accum_steps, eval_every=eval_every
    )
    print(f"\nDone. Loss trend: {result['loss_trend']}")
    print(f"Checkpoint: {result['ckpt_path']}")
