"""
subgoal_sft_train.py

SFT training for the HIGH-LEVEL VLM (see memory: hierarchical_architecture.md)
— the subgoal-selecting policy (policy.subgoal_vlm_policy.SubgoalVLMPolicy),
NOT the low-level flat-action warm-start sft_train.py trains
(policy.vlm_policy.VLMPolicy). Same base model and LoRA/training scaffolding,
different data format and target: the response here is
"{think}\n</think>\n<action>{subgoal_label}</action>" — a single category
token from SUBGOAL_LABELS, not four quantized action bins.

Reads : /model-cache/subgoal_sft_data.jsonl   (generated by generate_subgoal_sft_data.py)
Saves : /model-cache/checkpoints/subgoal_sft_warmstart/

Run with:
    modal run --detach scripts/subgoal_sft_train.py
    modal run --detach scripts/subgoal_sft_train.py --n-epochs 3 --lr 2e-5

    # Continue an existing LoRA adapter's weights (e.g. after a prompt-format
    # change like the 2026-07-17 "Block grasped" addition) instead of
    # training a fresh adapter from the base model:
    modal run --detach scripts/subgoal_sft_train.py --resume-from checkpoints/subgoal_sft_warmstart

Train/val loss tracking (2026-07-18):
    Every run writes a structured JSONL log to
    /model-cache/logs/subgoal_sft_metrics.jsonl regardless of W&B --
    one "step" record every 50 steps (train_loss so far this epoch) and
    one "epoch" record per epoch (train_loss, val_loss, best_val_loss).
    Download and plot with:
        modal volume get rl-harness-model-cache logs/subgoal_sft_metrics.jsonl ./artifacts/

    Optional W&B (same pattern as run_train_m6.py's GRPO trainer):
        modal secret create wandb-secret WANDB_API_KEY=<your-key>
        modal run --detach scripts/subgoal_sft_train.py --wandb-project rl-harness-robotics
"""

import modal
from think_then_act.modal_app import app, rl_image, model_volume, MODEL_CACHE_DIR


@app.function(
    image=rl_image,
    gpu="A10G",
    volumes={MODEL_CACHE_DIR: model_volume},
    timeout=3600 * 4,
    secrets=[modal.Secret.from_name("wandb-secret")],
)
def run_subgoal_sft_training(
    n_epochs         : int   = 8,     # upper bound only — early stopping ends the run sooner
    # Bumped 2e-5->1e-4 (2026-07-21): a run showed loss completely
    # plateaued (1.8076->1.8074 over 1100+ steps) alongside INCREASING
    # generation breakdown (garbled tokens, wrong actions) rather than
    # settling as training progressed — the opposite of what a converging
    # LoRA-only SFT run should look like. 2e-5 was carried over without
    # being tuned for this stage specifically (the project's own
    # lr=5e-6-is-critical finding is for the GRPO trainer's FULL-model RL,
    # a different sensitivity regime, not LoRA SFT). Not jumping to 2e-4
    # (which generic LoRA-SFT advice suggests) in one step -- 5x is
    # already a meaningful test of the plateau hypothesis without being
    # reckless; revisit further if this isn't enough.
    lr               : float = 1e-4,
    grad_accum_steps : int   = 8,
    lora_rank        : int   = 8,
    max_examples     : int   = 0,     # 0 = use all
    eval_every       : int   = 100,   # print generated think/action text every N steps (0 = off)
    label_smoothing  : float = 0.1,   # applied to the TRAIN loss only; val loss stays raw CE
                                       # so it's comparable across runs
    val_frac         : float = 0.1,   # fraction of EPISODES (not examples) held out
    patience         : int   = 2,     # stop if val loss hasn't improved for this many epochs
    min_delta        : float = 0.005, # minimum val-loss improvement to reset patience
    load_in_4bit     : bool  = False,
    resume_from      : str   = "",    # path to an existing LoRA checkpoint dir (e.g.
                                       # checkpoints/subgoal_sft_warmstart) to continue
                                       # training FROM, instead of a fresh LoRA adapter.
                                       # "" (default) = train a new adapter from the base
                                       # model, matching prior behavior. NOTE: the prompt
                                       # format the checkpoint was originally trained on
                                       # must be compatible with what THIS run's data uses
                                       # — resuming across a materially different prompt
                                       # distribution is a reasonable thing to try, not a
                                       # guaranteed win over starting fresh.
    wandb_project    : str   = "",    # "" (default) = no W&B, JSONL logging only.
                                       # Requires a `wandb-secret` Modal secret with
                                       # WANDB_API_KEY set (see module docstring).
) -> dict:
    import os, json, random, base64, io, time

    os.environ["HF_HOME"]            = MODEL_CACHE_DIR
    os.environ["TRANSFORMERS_CACHE"] = MODEL_CACHE_DIR

    import torch
    import torch.nn.functional as F
    from PIL import Image
    from qwen_vl_utils import process_vision_info
    from think_then_act.policy.subgoal_vlm_policy import SYSTEM_PROMPT, USER_PROMPT_TEMPLATE
    from think_then_act.policy.model_loader import (
        MODEL_ID, load_base_model, attach_lora, load_lora_checkpoint,
    )
    from think_then_act.reward.subgoal_reward import SUBGOAL_LABELS, DEFAULT_WEIGHTS

    print("\n" + "=" * 60)
    print("  HIGH-LEVEL VLM SFT TRAINING")
    print("=" * 60)

    # ------------------------------------------------------------------
    # Structured diagnostic log — persisted to the volume independent of
    # W&B, so every run leaves an offline-replayable train/val loss record
    # (same pattern as run_train_m6.py's GRPO trainer's log_jsonl). Appends
    # one JSON line per event and commits immediately: the file is tiny,
    # so the extra commit is cheap, and a spot-instance preemption loses at
    # most the in-flight step, not the whole log.
    # ------------------------------------------------------------------
    log_dir = os.path.join(MODEL_CACHE_DIR, "logs")
    os.makedirs(log_dir, exist_ok=True)
    metrics_log_path = os.path.join(log_dir, "subgoal_sft_metrics.jsonl")

    def log_jsonl(record: dict) -> None:
        record = {"ts": round(time.time(), 3), **record}
        with open(metrics_log_path, "a") as f:
            f.write(json.dumps(record) + "\n")
        model_volume.commit()

    print(f"\nDiagnostic log -> {metrics_log_path}")

    # ------------------------------------------------------------------
    # W&B setup (optional — only runs if WANDB_API_KEY is set + a project
    # is passed), same gating convention as run_train_m6.py.
    # ------------------------------------------------------------------
    wandb_enabled = bool(os.environ.get("WANDB_API_KEY") and wandb_project)
    if wandb_enabled:
        import wandb
        wandb.init(project=wandb_project, name=f"subgoal-sft-{int(time.time())}", config={
            "n_epochs": n_epochs, "lr": lr, "grad_accum_steps": grad_accum_steps,
            "lora_rank": lora_rank, "label_smoothing": label_smoothing,
            "val_frac": val_frac, "patience": patience, "resume_from": resume_from,
        })
        print(f"\nW&B logging -> project: {wandb_project}")
    else:
        print("\nW&B not configured — metrics logged to stdout + JSONL only.")

    # ------------------------------------------------------------------
    # 1. Load data
    # ------------------------------------------------------------------
    data_path = os.path.join(MODEL_CACHE_DIR, "subgoal_sft_data.jsonl")
    print(f"\n[1/4] Loading SFT data from {data_path}...")

    examples = []
    with open(data_path) as f:
        for line in f:
            examples.append(json.loads(line))

    if max_examples > 0:
        examples = examples[:max_examples]

    label_counts: dict = {label: 0 for label in SUBGOAL_LABELS}
    for ex in examples:
        label_counts[ex["subgoal"]] += 1
    print(f"  {len(examples)} examples  labels: {label_counts}")

    # Split by EPISODE, not example — adjacent steps within an episode/seeded
    # reset are highly correlated (same trajectory or same handoff state), so
    # an example-level split would leak train information into val and make
    # early stopping's signal untrustworthy. Same convention as sft_train.py.
    episode_ids = sorted({ex["episode"] for ex in examples if "episode" in ex})
    if episode_ids and val_frac > 0:
        rng = random.Random(0)
        rng.shuffle(episode_ids)
        n_val_eps = max(1, int(len(episode_ids) * val_frac))
        val_ep_ids = set(episode_ids[:n_val_eps])
        train_examples = [ex for ex in examples if ex["episode"] not in val_ep_ids]
        val_examples   = [ex for ex in examples if ex["episode"] in val_ep_ids]
    else:
        print("  [warn] no 'episode' field in data — skipping val split, no early stopping")
        train_examples, val_examples = examples, []

    print(f"  train={len(train_examples)} examples ({len(episode_ids) - len(val_ep_ids) if episode_ids and val_frac > 0 else '?'} episodes)"
          f"  val={len(val_examples)} examples ({len(val_ep_ids) if episode_ids and val_frac > 0 else 0} episodes)")

    examples = train_examples   # rest of the function trains on this name

    # ------------------------------------------------------------------
    # 2. Load model + LoRA
    # ------------------------------------------------------------------
    base_model, processor = load_base_model(
        MODEL_ID, cache_dir=MODEL_CACHE_DIR, load_in_4bit=load_in_4bit
    )

    if resume_from:
        print(f"\n[2/4] Resuming LoRA from checkpoint <- {resume_from} (4bit={load_in_4bit})...")
        if getattr(base_model, "is_loaded_in_4bit", False):
            # Same QLoRA prep attach_lora() does for a fresh adapter — needed
            # here too so a quantized base is equally prepared before PEFT
            # attaches the (resumed) adapter's trainable params to it.
            from peft import prepare_model_for_kbit_training
            base_model = prepare_model_for_kbit_training(
                base_model, use_gradient_checkpointing=True
            )
        model = load_lora_checkpoint(base_model, resume_from, trainable=True)
    else:
        # Widened from (q_proj, v_proj) 2026-07-21, alongside the lr bump
        # above -- with only q/v adapted, the model has limited capacity
        # to learn genuinely new computation (like combining dx/dy into a
        # Euclidean distance), mostly just re-weighting existing attention
        # patterns. Adding k_proj/o_proj gives it more room to actually
        # learn the operation. Not adding MLP layers (gate/up/down_proj)
        # in this same step -- keeps this one change isolated; a further
        # lever if attention-only widening isn't enough.
        lora_target_modules = ("q_proj", "k_proj", "v_proj", "o_proj")
        print(f"\n[2/4] Loading model + fresh LoRA (rank={lora_rank}, "
              f"target_modules={lora_target_modules}, 4bit={load_in_4bit})...")
        model = attach_lora(base_model, lora_rank=lora_rank, target_modules=lora_target_modules)

    model.print_trainable_parameters()
    model.train()

    optimizer = torch.optim.Adam(
        [p for p in model.parameters() if p.requires_grad], lr=lr
    )

    # ------------------------------------------------------------------
    # 3. Loss function for one example
    # ------------------------------------------------------------------
    def compute_loss(ex: dict, smoothing: float = 0.0) -> torch.Tensor:
        # Decode stored frame
        pil_image = Image.open(
            io.BytesIO(base64.b64decode(ex["frame_b64"]))
        ).resize((224, 224), Image.LANCZOS)

        # Rebuild user prompt — must match inference-time format exactly
        gripper_pos = [round(v, 4) for v in ex["gripper_pos"]]
        achieved    = [round(v, 4) for v in ex["achieved_goal"]]
        desired     = [round(v, 4) for v in ex["desired_goal"]]
        # ex["is_grasped"] is precomputed at data-generation time (see
        # generate_subgoal_sft_data.py's make_example) — reading it straight
        # from the stored row here, rather than recomputing from a partial
        # obs slice, since only gripper_pos (not finger widths) is persisted
        # per example.
        user_text = USER_PROMPT_TEMPLATE.format(
            gripper_pos=gripper_pos, achieved_goal=achieved, desired_goal=desired,
            is_grasped="yes" if ex["is_grasped"] else "no",
            table_height=DEFAULT_WEIGHTS.table_z,
        )

        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": [
                {"type": "image", "image": pil_image},
                {"type": "text",  "text": user_text},
            ]},
        ]

        # Prompt-only pass — find where response tokens start.
        # apply_chat_template with add_generation_prompt=True appends <think>
        # so the response is everything after that opening tag.
        text_input     = processor.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        img_inputs, vid_inputs = process_vision_info(messages)

        prompt_enc = processor(
            text=[text_input], images=img_inputs, videos=vid_inputs,
            return_tensors="pt", padding=True,
        )
        prompt_len = prompt_enc["input_ids"].shape[1]
        del prompt_enc

        # Target response: think content + </think> + action tag. <think> is
        # already in the prompt (from add_generation_prompt), so we only
        # provide what comes after it. Unlike sft_train.py's joined action
        # bins, the target here is a single category token straight from
        # ex["subgoal"] — nothing to encode/decode.
        response  = f"{ex['think']}\n</think>\n<action>{ex['subgoal']}</action>"
        full_text = text_input + response

        full_enc = processor(
            text=[full_text], images=img_inputs, videos=vid_inputs,
            return_tensors="pt", padding=True,
        ).to("cuda")

        outputs = model(**full_enc, use_cache=False)
        logits  = outputs.logits   # (1, seq_len, vocab_size)

        # Slice to response tokens only (same shift as _step_log_prob in trainer.py)
        resp_logits    = logits[:, prompt_len - 1 : -1, :]
        resp_token_ids = full_enc["input_ids"][:, prompt_len:]

        return F.cross_entropy(
            resp_logits.squeeze(0),
            resp_token_ids.squeeze(0),
            label_smoothing=smoothing,
        )

    def compute_val_loss() -> float:
        """Mean raw (unsmoothed) CE loss over the held-out episodes."""
        if not val_examples:
            return float("nan")
        model.eval()
        total = 0.0
        with torch.no_grad():
            for ex in val_examples:
                torch.cuda.empty_cache()
                total += compute_loss(ex, smoothing=0.0).item()
        model.train()
        return total / len(val_examples)

    # ------------------------------------------------------------------
    # 3b. Quick eval helper — generates think+action text for one fixed example
    # ------------------------------------------------------------------
    eval_ex = examples[0]   # fixed reference example (shuffled, so just first)

    def quick_eval(label: str) -> None:
        """Generate think+action text for the fixed eval example and print it."""
        model.eval()
        with torch.no_grad():
            pil_image = Image.open(
                io.BytesIO(base64.b64decode(eval_ex["frame_b64"]))
            ).resize((224, 224), Image.LANCZOS)

            gripper_pos = [round(v, 4) for v in eval_ex["gripper_pos"]]
            achieved    = [round(v, 4) for v in eval_ex["achieved_goal"]]
            desired     = [round(v, 4) for v in eval_ex["desired_goal"]]
            user_text   = USER_PROMPT_TEMPLATE.format(
                gripper_pos=gripper_pos, achieved_goal=achieved, desired_goal=desired,
                is_grasped="yes" if eval_ex["is_grasped"] else "no",
                table_height=DEFAULT_WEIGHTS.table_z,
            )
            messages = [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": [
                    {"type": "image", "image": pil_image},
                    {"type": "text",  "text": user_text},
                ]},
            ]
            text_input = processor.apply_chat_template(
                messages, tokenize=False, add_generation_prompt=True
            )
            img_inputs, vid_inputs = process_vision_info(messages)
            enc = processor(
                text=[text_input], images=img_inputs, videos=vid_inputs,
                return_tensors="pt", padding=True,
            ).to("cuda")

            # 400, not 256 -- every template now shows full worked arithmetic
            # (2026-07-17), pushing the longest target (~140 tokens) close
            # enough to 256 that an early-training, still-rambling model can
            # get truncated before reaching </action> — see
            # eval_subgoal_vlm.py's max_new_tokens comment for the confirmed
            # failure mode (98% parse failures on an epoch-2 checkpoint at
            # a 200-token cap).
            out        = model.generate(**enc, max_new_tokens=400, do_sample=False,
                                        stop_strings=["</action>"], tokenizer=processor.tokenizer)
            new_tokens = out[0][enc["input_ids"].shape[1]:]
            text       = processor.tokenizer.decode(new_tokens, skip_special_tokens=True)

        model.train()
        print(f"\n  [EVAL {label}]")
        print(f"  state: achieved={achieved}  desired={desired}  source={eval_ex.get('source')}")
        print(f"  target subgoal: {eval_ex['subgoal']}")
        # 800, not 400 -- this is a PRINT-time character slice, unrelated to
        # max_new_tokens (already 400 tokens). The align_xy/close_gripper/
        # etc. worked-arithmetic templates run ~420-450 characters alone, so
        # a 400-char print cap routinely cut the logged text off mid-word
        # right around <action> (looked like a real truncation bug but
        # wasn't -- confirmed 2026-07-17 by checking this line directly).
        print(f"  generated: {text[:800]}")
        print()

    # ------------------------------------------------------------------
    # 4. Training loop
    # ------------------------------------------------------------------
    steps_per_epoch = len(examples)
    total_steps     = n_epochs * steps_per_epoch
    est_min         = total_steps * 0.5 / 60   # ~0.5 s/step on A10G
    print(f"\n[3/4] Training: {n_epochs} epochs  lr={lr}  grad_accum={grad_accum_steps}...")
    print(f"  {total_steps} total steps  estimated {est_min:.0f}–{est_min*2:.0f} min on A10G")

    loss_history     = []
    val_loss_history = []
    global_step      = 0
    best_val_loss    = float("inf")
    epochs_no_improve = 0
    stopped_early    = False

    if eval_every > 0:
        quick_eval("before training")

    for epoch in range(n_epochs):
        random.shuffle(examples)
        epoch_loss  = 0.0
        optimizer.zero_grad()

        for i, ex in enumerate(examples):
            torch.cuda.empty_cache()

            loss = compute_loss(ex, smoothing=label_smoothing) / grad_accum_steps
            loss.backward()
            epoch_loss += loss.item() * grad_accum_steps

            # Step whenever accumulation window fills or we hit the last example
            if (i + 1) % grad_accum_steps == 0 or (i + 1) == len(examples):
                torch.nn.utils.clip_grad_norm_(
                    [p for p in model.parameters() if p.requires_grad], 1.0
                )
                optimizer.step()
                optimizer.zero_grad()

            global_step += 1

            if (i + 1) % 50 == 0:
                avg = epoch_loss / (i + 1)
                print(f"  epoch {epoch+1}  step {i+1}/{len(examples)}  loss={avg:.4f}")
                log_jsonl({"type": "step", "epoch": epoch + 1, "global_step": global_step,
                           "train_loss": round(avg, 4)})
                if wandb_enabled:
                    wandb.log({"train/loss": avg, "epoch": epoch + 1}, step=global_step)

            if eval_every > 0 and global_step % eval_every == 0:
                quick_eval(f"epoch {epoch+1} step {i+1}")

            if global_step % 500 == 0:
                ckpt_path = os.path.join(MODEL_CACHE_DIR, "checkpoints", f"subgoal_sft_step_{global_step}")
                os.makedirs(ckpt_path, exist_ok=True)
                model.save_pretrained(ckpt_path)
                model_volume.commit()
                print(f"  [checkpoint] step {global_step} → {ckpt_path}")

        avg_epoch_loss = epoch_loss / len(examples)
        loss_history.append(round(avg_epoch_loss, 4))
        val_loss = compute_val_loss()
        val_loss_history.append(round(val_loss, 4))
        print(f"  === Epoch {epoch+1} complete  train_loss={avg_epoch_loss:.4f}  "
              f"val_loss={val_loss:.4f} ===\n")
        if eval_every > 0:
            quick_eval(f"end of epoch {epoch+1}")

        # Always keep a per-epoch checkpoint (cheap, useful for post-hoc comparison).
        epoch_ckpt = os.path.join(MODEL_CACHE_DIR, "checkpoints", f"subgoal_sft_epoch_{epoch+1}")
        os.makedirs(epoch_ckpt, exist_ok=True)
        model.save_pretrained(epoch_ckpt)

        # subgoal_sft_warmstart (the canonical downstream-consuming pointer)
        # only advances on a real val-loss improvement, instead of always
        # tracking the latest epoch — same rationale as sft_train.py's
        # sft_warmstart (a prior run there pointed at an overfit epoch
        # despite an earlier epoch having lower val loss).
        val_signal = val_loss if val_examples else avg_epoch_loss
        improved   = val_signal < best_val_loss - min_delta
        if improved:
            best_val_loss     = val_signal
            epochs_no_improve = 0
            ckpt_path = os.path.join(MODEL_CACHE_DIR, "checkpoints", "subgoal_sft_warmstart")
            os.makedirs(ckpt_path, exist_ok=True)
            model.save_pretrained(ckpt_path)
            model_volume.commit()
            print(f"  [best] val_loss improved → subgoal_sft_warmstart updated ← {epoch_ckpt}")
        else:
            epochs_no_improve += 1
            model_volume.commit()
            print(f"  Checkpoint saved → {epoch_ckpt}  "
                  f"(val_loss did not improve, {epochs_no_improve}/{patience})")

        log_jsonl({"type": "epoch", "epoch": epoch + 1, "global_step": global_step,
                   "train_loss": round(avg_epoch_loss, 4), "val_loss": round(val_loss, 4),
                   "best_val_loss": round(best_val_loss, 4), "improved": improved})
        if wandb_enabled:
            wandb.log({"train/epoch_loss": avg_epoch_loss, "val/loss": val_loss,
                       "val/best_loss": best_val_loss, "epoch": epoch + 1}, step=global_step)

        if val_examples and epochs_no_improve >= patience:
            print(f"  [early stop] no val_loss improvement for {patience} epochs — stopping.")
            stopped_early = True
            break

    # ------------------------------------------------------------------
    # 5. Final summary
    # ------------------------------------------------------------------
    print(f"  Train loss trend: {loss_history}")
    print(f"  Val loss trend  : {val_loss_history}")
    if stopped_early:
        print(f"  Stopped early — best val_loss={best_val_loss:.4f}")
    print(f"  Metrics log -> {metrics_log_path}")
    print("=" * 60)

    if wandb_enabled:
        wandb.finish()

    return {
        "status"        : "PASS",
        "stopped_early" : stopped_early,
        "best_val_loss" : round(best_val_loss, 4) if val_examples else None,
        "val_loss_trend": val_loss_history,
        "n_examples"    : len(examples),
        "n_epochs"      : n_epochs,
        "loss_trend"    : loss_history,
        "ckpt_path"     : ckpt_path,
    }


# ---------------------------------------------------------------------------
# Local entrypoint
# ---------------------------------------------------------------------------

@app.local_entrypoint()
def main(
    n_epochs         : int   = 8,
    lr               : float = 1e-4,
    grad_accum_steps : int   = 8,
    lora_rank        : int   = 8,   # was never forwarded from here before 2026-07-21 -- always
                                     # silently used run_subgoal_sft_training's own default, so
                                     # there was no way to actually change it via CLI.
    eval_every       : int   = 100,
    label_smoothing  : float = 0.1,
    val_frac         : float = 0.1,
    patience         : int   = 2,
    load_in_4bit     : bool  = False,
    resume_from      : str   = "",   # e.g. checkpoints/subgoal_sft_warmstart
    wandb_project    : str   = "",   # "" = no W&B, JSONL logging only (see module docstring)
):
    print(f"\nDispatching high-level VLM SFT training to Modal (A10G)...")
    print(f"  epochs<={n_epochs}  lr={lr}  grad_accum={grad_accum_steps}  lora_rank={lora_rank}  "
          f"eval_every={eval_every}")
    print(f"  label_smoothing={label_smoothing}  val_frac={val_frac}  patience={patience}  "
          f"4bit={load_in_4bit}  resume_from={resume_from or '(fresh LoRA)'}  "
          f"wandb_project={wandb_project or '(none)'}\n")

    resume_path = (
        f"{MODEL_CACHE_DIR}/{resume_from}" if resume_from and not resume_from.startswith(MODEL_CACHE_DIR)
        else resume_from
    )
    handle = run_subgoal_sft_training.spawn(
        n_epochs=n_epochs, lr=lr, grad_accum_steps=grad_accum_steps, lora_rank=lora_rank,
        eval_every=eval_every,
        label_smoothing=label_smoothing, val_frac=val_frac, patience=patience,
        load_in_4bit=load_in_4bit, resume_from=resume_path, wandb_project=wandb_project,
    )
    print(f"Job spawned. Function call ID: {handle.object_id}")
    print(f"Monitor at https://modal.com")
    print(f"Checkpoint will be saved to: {MODEL_CACHE_DIR}/checkpoints/subgoal_sft_warmstart")
    print(f"Metrics JSONL will be at: {MODEL_CACHE_DIR}/logs/subgoal_sft_metrics.jsonl")
